### ISSUE TITLE
Transcripts are Missing Caption Files

### ISSUE THREAD

**Issue by jfc3** [A11YChi/transcripts#1]
It looks like all the transcript files from "2017-05-18-GAAD.md" and below are missing their transcripts/caption file in the list. When I click the "Source recording" link, it gives me a GitHub 404 page.

I'm not sure if this is supposedly the video to watch to create a transcript or a link to the caption file to be formatted.

In the other ones are you looking for people to remove the date and timestamps from the ones you have caption files from or to create those?

jfc iii

**Comment by deconspray** [comment]
John, you are correct. We do need to get the raw captions placed into this repository for 5/18/2017 moving forward. The 5/18/2017 GAAD event is actually not edited yet, so we won't have those captions until that post-event edited is completed.

For the available ones, yes, just looking to remove date/time stamp, and format the lines of text into understandable paragraphs with speakers in brackets, as the completed ones have been formatted.

Thanks!

Dennis

**Comment by jfc3** [comment]
@deconspray,

Thanks, I only wanted to point it out in case there was a problem.

Are the "Source recording" links supposed to point to the videos? If so correcting them would at least fix the 404 errors in the short term while you get the captions loaded to the files.

**Comment by deconspray** [comment]
Hey John, thanks again. I resolved any links to the videos that were broken. I'm also hopefully to make a dent in the backlog we have here. Look for updates and progress soon.

Dennis

**Comment by nickttng** [comment]
@deconspray Has this issue been resolved? If so, feel free to close or I can.
